### ISSUE TITLE
build出现问题

### ISSUE THREAD

**Issue by SilverBiscuit** [zjlywjh001/phrackCTF-Personal-Docker#3]
Sending build context to Docker daemon  95.85MB
Step 1/48 : FROM ubuntu:14.04
 ---> 578c3e61a98c
Step 2/48 : MAINTAINER Jarvis <jarvis@jarviswang.me>
 ---> Using cache
 ---> e03b332d207c
Step 3/48 : RUN locale-gen en_GB.UTF-8
 ---> Using cache
 ---> 712d92571a68
Step 4/48 : ENV LANG en_GB.UTF-8
 ---> Using cache
 ---> fcb88bfbc4f9
Step 5/48 : ENV LC_CTYPE en_GB.UTF-8
 ---> Using cache
 ---> a572dc2aec70
Step 6/48 : RUN rm /bin/sh && ln -s /bin/bash /bin/sh
 ---> Using cache
 ---> 67ad84632ed8
Step 7/48 : RUN 	sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && 	apt-get update && 	apt-get install -y wget curl build-essential software-properties-common python-software-properties nano
 ---> Using cache
 ---> e9bf7ec9fdd6
Step 8/48 : RUN 	sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && 	apt-get update && 	apt-get install -y wget curl build-essential software-properties-common python-software-properties nano && 	add-apt-repository ppa:openjdk-r/ppa && 	apt-get update && 	apt-get -y install openjdk-8-jdk && 	update-alternatives --config java && 	export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre && 	export JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
 ---> Using cache
 ---> c977d265e823
Step 9/48 : RUN apt-get update && 	apt-get install -y ca-certificates-java && 	apt-get clean && 	update-ca-certificates -f && 	rm -rf /var/lib/apt/lists/* && 	rm -rf /var/cache/oracle-jdk8-installer;
 ---> Using cache
 ---> 6c7d74d20d85
Step 10/48 : ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/jre
 ---> Using cache
 ---> d48b05853537
Step 11/48 : RUN 	groupadd tomcat && 	useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && 	cd /tmp && 	curl -O http://mirrors.advancedhosters.com/apache/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz && 	mkdir /opt/tomcat && 	tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1 && cd /opt/tomcat && 	chgrp -R tomcat /opt/tomcat && 	chmod -R g+r conf && 	chmod g+x conf && 	chown -R tomcat webapps/ work/ temp/ logs/
 ---> Running in c8fac4b882d3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   337  100   337    0     0    580      0 --:--:-- --:--:-- --:--:--   580

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c groupadd tomcat && 	useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && 	cd /tmp && 	curl -O http://mirrors.advancedhosters.com/apache/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz && 	mkdir /opt/tomcat && 	tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1 && cd /opt/tomcat && 	chgrp -R tomcat /opt/tomcat && 	chmod -R g+r conf && 	chmod g+x conf && 	chown -R tomcat webapps/ work/ temp/ logs/' returned a non-zero code: 2

**Comment by zjlywjh001** [comment]
tomcat地址替换一下，换成最新的就行
http://mirror.cogentco.com/pub/apache/tomcat/tomcat-8/v8.5.31/bin/apache-tomcat-8.5.31.tar.gz

**Comment by XTeam-Wing** [comment]
不行，师傅为啥不直接提交到docker啊。
tep 11/48 : RUN 	groupadd tomcat && 	useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && 	cd /tmp && 	curl -O http://mirror.cogentco.com/pub/apache/tomcat/tomcat-8/v8.5.31/bin/apache-tomcat-8.5.31.tar.gz && 	mkdir /opt/tomcat && 	tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1 && 	cd /opt/tomcat && 	chgrp -R tomcat /opt/tomcat && 	chmod -R g+r conf && 	chmod g+x conf && 	chown -R tomcat webapps/ work/ temp/ logs/
 ---> Running in 32075c964dd1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   264  100   264    0     0    276      0 --:--:-- --:--:-- --:--:--   276

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by XTeam-Wing** [comment]
HTTPステータス 404 - Not Found
Type ステータスレポート

メッセージ /phrackCTF

説明 The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/8.5.32

启动之后404

**Comment by zjlywjh001** [comment]
> HTTPステータス 404 - Not Found
> Type ステータスレポート
> 
> メッセージ /phrackCTF
> 
> 説明 The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
> 
> Apache Tomcat/8.5.32
> 
> 启动之后404

启动之前先仔细读一下说明里面，config/spring-mail.xml这个文件里面把邮件服务器的帐号配好，然后邮件模板config/mail.properties里面把发件人的邮件地址改成邮件服务器里面你用的发件人邮件地址，如果不配好直接编译启动的话，就会404的。

**Comment by zjlywjh001** [comment]
> Sending build context to Docker daemon 95.85MB
> Step 1/48 : FROM ubuntu:14.04
> ---> 578c3e61a98c
> Step 2/48 : MAINTAINER Jarvis [jarvis@jarviswang.me](mailto:jarvis@jarviswang.me)
> ---> Using cache
> ---> e03b332d207c
> Step 3/48 : RUN locale-gen en_GB.UTF-8
> ---> Using cache
> ---> 712d92571a68
> Step 4/48 : ENV LANG en_GB.UTF-8
> ---> Using cache
> ---> fcb88bfbc4f9
> Step 5/48 : ENV LC_CTYPE en_GB.UTF-8
> ---> Using cache
> ---> a572dc2aec70
> Step 6/48 : RUN rm /bin/sh && ln -s /bin/bash /bin/sh
> ---> Using cache
> ---> 67ad84632ed8
> Step 7/48 : RUN sed -i 's/# (._multiverse$)/\1/g' /etc/apt/sources.list && apt-get update && apt-get install -y wget curl build-essential software-properties-common python-software-properties nano ---> Using cache ---> e9bf7ec9fdd6 Step 8/48 : RUN sed -i 's/# (._multiverse$)/\1/g' /etc/apt/sources.list && apt-get update && apt-get install -y wget curl build-essential software-properties-common python-software-properties nano && add-apt-repository ppa:openjdk-r/ppa && apt-get update && apt-get -y install openjdk-8-jdk && update-alternatives --config java && export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre && export JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre ---> Using cache ---> c977d265e823 Step 9/48 : RUN apt-get update && apt-get install -y ca-certificates-java && apt-get clean && update-ca-certificates -f && rm -rf /var/lib/apt/lists/_ && rm -rf /var/cache/oracle-jdk8-installer; ---> Using cache ---> 6c7d74d20d85 Step 10/48 : ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/jre ---> Using cache ---> d48b05853537 Step 11/48 : RUN groupadd tomcat && useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && cd /tmp && curl -O http://mirrors.advancedhosters.com/apache/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz && mkdir /opt/tomcat && tar xzvf apache-tomcat-8_tar.gz -C /opt/tomcat --strip-components=1 && cd /opt/tomcat && chgrp -R tomcat /opt/tomcat && chmod -R g+r conf && chmod g+x conf && chown -R tomcat webapps/ work/ temp/ logs/
> ---> Running in c8fac4b882d3
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 337 100 337 0 0 580 0 --:--:-- --:--:-- --:--:-- 580
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> The command '/bin/sh -c groupadd tomcat && useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && cd /tmp && curl -O http://mirrors.advancedhosters.com/apache/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz && mkdir /opt/tomcat && tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1 && cd /opt/tomcat && chgrp -R tomcat /opt/tomcat && chmod -R g+r conf && chmod g+x conf && chown -R tomcat webapps/ work/ temp/ logs/' returned a non-zero code: 2

fixed on ecf99470929b1965808e4e1d073f337b32339c55
